blank_issues_enabled: true
contact_links:
  - name: Shineway official website
    url: https://www.shineway.tech/
    about: Learn more about the company initiating and maintaining this open-source project.
